name: lainisha
description: A Cross-Platform, Open-Source Admin Framework for Flutter
version: 2024.9.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  adaptive_chameleon_theme: ^2024.9.0
  cached_network_image: ^3.4.1
  csv: ^6.0.0
  dio: ^5.7.0
  flutter:
    sdk: flutter

  get_it: ^7.7.0
  go_router: ^14.2.7
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: any
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/branding/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Black.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-ExtraLight.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Light.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Regular.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Thin.ttf

flutter_gen:
  assets:
    enabled: true
    outputs:
      # Set to true if you want this package to be a package dependency
      # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
      package_parameter_enabled: true

  output: lib/src/generated/
  line_length: 80
